*-- (c) Microsoft Corporation 1995

*-- STRINGS.H
*-- Include this file where needed for localization
*-- purposes

*-- Messagebox Titles
#DEFINE ERRORTITLE_LOC      "Error"
#DEFINE TASTRADE_LOC        "Módulo de Facturación"

*-- Toolbar names
#DEFINE TB_FORMDESIGNER_LOC  "Diseñador de formularios"
#DEFINE TB_STANDARD_LOC      "Estándar"
#DEFINE TB_LAYOUT_LOC        "Diseño"
#DEFINE TB_QUERY_LOC		 "Diseñador de consultas"
#DEFINE TB_VIEWDESIGNER_LOC  "Diseñador de vistas"
#DEFINE TB_COLORPALETTE_LOC  "Paleta de colores"
#DEFINE TB_FORMCONTROLS_LOC  "Controles de formularios"
#DEFINE TB_DATADESIGNER_LOC  "Diseñador de bases de datos"
#DEFINE TB_REPODESIGNER_LOC  "Diseñador de informes"
#DEFINE TB_REPOCONTROLS_LOC  "Controles de informes"
#DEFINE TB_PRINTPREVIEW_LOC  "Vista preliminar"
#DEFINE WIN_COMMAND_LOC		 "Comandos"			&& Ventana Comandos


*-- Messagebox Messages
#DEFINE FILENOTEXIST_LOC	"El archivo no existe: "
#DEFINE BADPASSWORD_LOC		"La contraseña no es válida. (Vea el cuadro de texto Sugerencia)"
#DEFINE BADNAME_LOC			"No se encuentra el nombre."
#DEFINE BADUPDATE_LOC		"No se puede actualizar: volverá al valor original."
#DEFINE SAVECHANGES_LOC		"¿Desea guardar los cambios?"
#DEFINE ASKDELETE_LOC		"¿Realmente desea eliminar esta información?"
#DEFINE TAGNOTFOUND_LOC		"No se encuentra la etiqueta del índice."
#DEFINE REPORTNOTFOUND_LOC	"No se encuentra el archivo de informe."
#DEFINE PRINTERNOTREADY_LOC	"La impresora no está preparada."
#DEFINE NORECSMATCHED_LOC	"Ningún registro cumple los criterios."
#DEFINE DELETEREC_LOC		"¿Realmente desea eliminar este registro?"
#DEFINE DELETEWARN_LOC      "Advertencia de eliminación"
#DEFINE AVAILABLECREDIT_LOC	"Crédito disponible"
#DEFINE NOTYET_LOC          "En construcción"
#DEFINE CUSTIDEXISTS_LOC    "El Código del cliente ya existe. Escriba otro distinto."
#DEFINE PRODIDEXISTS_LOC    "El Codigo para este registro ya existe."
#DEFINE NOLASTORDER_LOC		"El cliente no tiene ningún factura previa."
#DEFINE CUSTFIRSTORDER_LOC  "La última factura del cliente es el actual."
#DEFINE TODAYORLATER_LOC    "La fecha debe ser la de hoy o posterior."
#DEFINE DATERANGEERROR_LOC  "La fecha 'Hasta' no puede ser anterior a la fecha 'Desde'."
#DEFINE ADDCUSTOMER_LOC		"¿Desea agregar este cliente al archivo maestro de clientes?"
#DEFINE ADDPRODUCTS_LOC		"Este producto no existe, ¿Desea crearlo?"
#DEFINE NOTHINGTOPRINT_LOC  "No hay información disponible para imprimir."
#DEFINE PASSWORDEMPTY_LOC	"La nueva contraseña no puede estar en blanco."
#DEFINE PSWDNOTCNFRM_LOC    "No se puede confirmar la nueva contraseña. Inténtelo de nuevo."
#DEFINE NOPSWDENTERED_LOC	"La contraseña anterior no es valida. ¿Desea continuar?"
#DEFINE FILESAVEDAS_LOC		"Archivo guardado como "
#DEFINE ORDHASITEMS_LOC		"Una factura debe tener al menos un artículo."
#DEFINE CUSTOVERMAX_LOC		"El cliente ha excedido su limite de credito en "
#DEFINE CUSTUNDERMIN_LOC    "El Monto total de la factura del cliente debe ser al menos "
#DEFINE SAVEANYWAY_LOC      "¿Desea continuar de todas formas?"
#DEFINE VALIDATING_LOC      "Validando ..."
#DEFINE PRINTING_LOC        "Imprimiendo ..."
#DEFINE VIEWCODEPRINT_LOC	"Este informe puede ser muy largo. ¿Desea continuar?"
#DEFINE VIEWCSDTYPRINT_LOC  "Este informe puede ser muy largo. ¿Desea continuar?"
#DEFINE METHOD_LOC          "Método: "
#DEFINE LINENUM_LOC			"Línea: "
#DEFINE CUSTNOORD_LOC		"El cliente no tiene facturas."
#DEFINE SELCUSTFIRST_LOC    "Primero debe seleccionar un cliente."
#DEFINE CANNOTQUIT_LOC      "No se puede salir desde el sistema de facturación."
#DEFINE ADDNEWREC_LOC		"Este era el último registro. ¿Desea agregar uno nuevo?"
#DEFINE ENTERADDMODE_LOC    "No hay ningún registro en el archivo. Pasará al modo 'Agregar'."
#DEFINE NOEMPLOYEES_LOC		"No hay ningún vendedor en el archivo."
#DEFINE INSEMPLOYEE_LOC		"Todos los vendedores deben estar asignados a un grupo."
#DEFINE INSPRODUCT_LOC      "A todos los productos se les debe asignar un proveedor y una categoría."
#DEFINE INSORDER_LOC        "Todas las facturas deben tener a quien se le envia."
#DEFINE TABLERULEFAIL_LOC	"E r r o r  en la tabla."
#DEFINE ITEMNOTSAVED_LOC	"Los artículos marcados no se han agregado a la factura. ¿Desea descartar los artículos marcados?"
#DEFINE CLASSBROWERR_LOC	"Esta clase no se puede utilizar fuera de la aplicación."
*-- Trigger error messages
#DEFINE INSERTTRIGFAIL_LOC  "Error del desencadenador Insert."
#DEFINE UPDATETRIGFAIL_LOC  "Error del desencadenador Update."
#DEFINE DELETETRIGFAIL_LOC  "Error del desencadenador Delete."
#DEFINE DELCATEGORY_LOC		"Los productos pertenecen a esta categoría. No se puede eliminar."
#DEFINE DELCUSTOMER_LOC		"El cliente tiene facturas. No se puede eliminar."
#DEFINE DELEMPLOYEE_LOC		"El vendedor existe en las facturas. No se puede eliminar."
#DEFINE DELPRODUCT_LOC      "El producto existe en los artículos de facturas. No se puede eliminar."
#DEFINE DELSUPPLIER_LOC		"Los productos los suministra este proveedor. No se puede eliminar."
#DEFINE DELSHIPPER_LOC      "La compañía de envío existe en las facturas. No se puede eliminar."

*-- Other strings
#DEFINE ADDPICTURE_LOC      "Agregar imagen"
#DEFINE CHANGEPICTURE_LOC	"Cambiar imagen"
#DEFINE SELECTBUTTON_LOC    "Seleccionar"
#DEFINE VERSION_LOC			"1.1"
#DEFINE COPYRIGHT_LOC		"Copyright 2013 Systems Solutions Inc."
#DEFINE RIGHTSRSRVD_LOC		"Reservados todos los derechos"
#DEFINE ADDITEM_LOC			"Agregar producto"
#DEFINE REMOVEITEM_LOC      "Quitar producto"
#DEFINE INFSAVED_LOC        "Información Guardada"
#DEFINE REINDEXING_LOC      "Reindexando: "
#DEFINE DONE_LOC            "Proceso concluido con exito ..."
#DEFINE LOWERNOTFOUND_LOC	" no se encuentra."
#DEFINE ABOUT_LOC			"Acerca de "
#DEFINE VERSIONLABEL_LOC    "Versión "
#DEFINE LOWERFOR_LOC        " para "
#DEFINE UPDATEORDER_LOC		"Actualizando la factura"
#DEFINE MAXCREDIORDER_LOC   "Factura excede MONTO DE CREDITO DISPONIBLE"
#DEFINE ADDPRODUCTO_LOC     "Este producto se ha agotado en inventario"
#DEFINE NIVELPRODUCTO_LOC   "Solo queda en existencia de este producto"
#DEFINE PRODUCTEXPIRE_LOC   "Este producto ha expirado, ¿Desea continuar?"
#DEFINE TITULO_WINDOW_LOC   "Notificación"
